version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda_frontend
    restart: unless-stopped
    ports:
      '80:80'
  networks: frontend_net

networks:
  frontend_net:
    driver: bridge